cloud:
  aws:
    credentials:
      access-key: <<key>>
      secret-key: <<key>>
    region:
      static: us-east-2
    stack:
      auto: false

spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB
  application:
    bucket:
      name: Amazon-S3
      
server:
  port: 9090